//! Three-source oracle grid for the exported descriptive statistics.
//! Conventions pinned: var/sd ddof=1 (Sample) and ddof=0 (Population);
//! skewness = Fisher–Pearson g1 (biased, scipy skew default); kurtosis =
//! Fisher excess (biased, scipy kurtosis default). Fixtures generated by
//! scripts/gen_oracle.py descriptives — mpmath truth, scipy+R cross-check.
use commonstats::{Ddof, cov, kurtosis, mean, median, pearson, sd, skewness, var};
use serde::Deserialize;

mod common;
use common::{Tol, assert_close};

fn read_fixture() -> Fixture {
    let p = format!(
        "{}/tests/fixtures/descriptives.json",
        env!("CARGO_MANIFEST_DIR")
    );
    serde_json::from_str(&std::fs::read_to_string(p).unwrap()).unwrap()
}

#[derive(Deserialize)]
struct Fixture {
    unary: Vec<UnaryCase>,
    binary: Vec<BinaryCase>,
}

#[derive(Deserialize)]
struct UnaryCase {
    xs: Vec<f64>,
    mean: f64,
    var_sample: f64,
    var_pop: f64,
    sd_sample: f64,
    sd_pop: f64,
    median: f64,
    skewness: f64,
    kurtosis: f64,
}

#[derive(Deserialize)]
struct BinaryCase {
    xs: Vec<f64>,
    ys: Vec<f64>,
    cov: f64,
    pearson: f64,
}

// Class-C stat tolerance: rel 1e-12, abs floor 1e-14.
const TOL: Tol = Tol {
    rel: 1e-12,
    abs: 1e-14,
};

#[test]
fn descriptives_match_oracle() {
    let f = read_fixture();
    for (i, c) in f.unary.iter().enumerate() {
        let lbl = format!("unary[{i}]");
        let got_mean = mean(&c.xs).unwrap();
        let got_vs = var(&c.xs, Ddof::Sample).unwrap();
        let got_vp = var(&c.xs, Ddof::Population).unwrap();
        let got_sds = sd(&c.xs, Ddof::Sample).unwrap();
        let got_sdp = sd(&c.xs, Ddof::Population).unwrap();
        let got_med = median(&c.xs).unwrap();
        let got_skew = skewness(&c.xs).unwrap();
        let got_kurt = kurtosis(&c.xs).unwrap();
        assert_close(&format!("{lbl} mean"), got_mean, c.mean, TOL);
        assert_close(&format!("{lbl} var_sample"), got_vs, c.var_sample, TOL);
        assert_close(&format!("{lbl} var_pop"), got_vp, c.var_pop, TOL);
        assert_close(&format!("{lbl} sd_sample"), got_sds, c.sd_sample, TOL);
        assert_close(&format!("{lbl} sd_pop"), got_sdp, c.sd_pop, TOL);
        assert_close(&format!("{lbl} median"), got_med, c.median, TOL);
        assert_close(&format!("{lbl} skewness"), got_skew, c.skewness, TOL);
        assert_close(&format!("{lbl} kurtosis"), got_kurt, c.kurtosis, TOL);
    }
    for (i, c) in f.binary.iter().enumerate() {
        let lbl = format!("binary[{i}]");
        let got_cov = cov(&c.xs, &c.ys).unwrap();
        let got_pea = pearson(&c.xs, &c.ys).unwrap();
        assert_close(&format!("{lbl} cov"), got_cov, c.cov, TOL);
        assert_close(&format!("{lbl} pearson"), got_pea, c.pearson, TOL);
    }
}
